import React from "react";
import Head from "next/head";
import styles from "../../../styles/StarRepo/StarRepoPage.module.scss";
import Navbar from "../../../components/Navbar";
import Footer from "../../../components/Footer";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"; // Import the FontAwesomeIcon component
import {
  faArrowRight,
  faCogs,
  faArrowUpRightFromSquare,
} from "@fortawesome/free-solid-svg-icons"; // import the icons you need
import { faGithub } from "@fortawesome/free-brands-svg-icons"; //

function User({ data }) {
  //   return <div>{`Testing the data => ${data}`}</div>;
  //   console.log("data", data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Github-Readme-Design</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar title={"Starred-Repo"} />
      <main className={styles.outerContainer}>
        <div className={styles.containerForBoxAndTitle}>
          <div className={styles.selectBox}>
            <div className={styles.selectBoxOne}>
              Please select the Repo below:
            </div>
            <div className={styles.selectBoxTwo}>
              <select className={styles.select}>
                <option value="choose_repo">Choose Repo</option>
                {data?.map((item, index) => (
                  <option value={item} key={index}>
                    {item?.name}
                  </option>
                ))}
              </select>
            </div>
          </div>
          <div className={styles.titleBox}>
            <div className={styles.boxOne}>#Preview</div>
            <div className={styles.boxTwo}>
              <select className={styles.darkLightMode}>
                <option value="light">Light</option>
                <option value="dark">Dark</option>
              </select>
              <button
                className={styles.copyButton}
                onClick={(e) => {
                  e.preventDefault();
                  alert("URL Coppied!");
                }}
              >
                Copy URL
              </button>
            </div>
          </div>
        </div>
        {/* ::::::::::::::::::::::::::::::::::::: */}
        <div className={styles.designBackground}></div>
        <div className={styles.helpus}>
          Please help us to improve this for everyone need Thank You!
          <a
            className={styles.projectButton}
            href="https://github.com/hirishu10/github-readme-design"
            target="_blank"
            rel="noopener noreferrer"
          >
            <FontAwesomeIcon
              icon={faArrowUpRightFromSquare}
              size={"1x"}
              style={{
                marginLeft: 10,
                transition: "0.2s",
              }}
            />
          </a>
        </div>
      </main>
      <Footer />
    </div>
  );
}

export default User;

// This gets called on every request
export async function getServerSideProps(context) {
  let name = context?.params?.user;
  const res = await fetch(`https://api.github.com/users/${name}/starred`);
  const data = await res.json();
  return {
    props: {
      data: data,
    },
  };
}
