import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
// import styles from "../styles/Home.module.css";
import styles from "../styles/Home.module.scss";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"; // Import the FontAwesomeIcon component
import { faArrowRight, faCogs } from "@fortawesome/free-solid-svg-icons"; // import the icons you need
import { faGithub } from "@fortawesome/free-brands-svg-icons"; // import the icons you need
//
import fs from "fs";
import path from "path";
import { convertCookieData } from "../utils/convertCookieData";
//
import $ from "jquery";
import AllCard from "../components/AllCard";

const Home: NextPage = (data) => {
  const [errMesage, setErrMesage] = useState(false);
  const [succMessage, setSuccMessage] = useState(false);
  const [loadMessage, setLoadMessage] = useState("...");
  const [inputValue, setInputValue] = useState("");
  // const [cookieData, setCookieData] = useState(""); // This will for future release

  const testGit = {
    login: "hirishu10",
    id: 95957258,
    node_id: "U_kgDOBbgxCg",
    avatar_url: "https://avatars.githubusercontent.com/u/95957258?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/hirishu10",
    html_url: "https://github.com/hirishu10",
    followers_url: "https://api.github.com/users/hirishu10/followers",
    following_url:
      "https://api.github.com/users/hirishu10/following{/other_user}",
    gists_url: "https://api.github.com/users/hirishu10/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/hirishu10/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/hirishu10/subscriptions",
    organizations_url: "https://api.github.com/users/hirishu10/orgs",
    repos_url: "https://api.github.com/users/hirishu10/repos",
    events_url: "https://api.github.com/users/hirishu10/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/hirishu10/received_events",
    type: "User",
    site_admin: false,
    name: "Rishu Chowdhary",
    company: null,
    blog: "",
    location: null,
    email: null,
    hireable: true,
    bio: null,
    twitter_username: null,
    public_repos: 14,
    public_gists: 0,
    followers: 0,
    following: 0,
    created_at: "2021-12-11T07:43:50Z",
    updated_at: "2022-04-14T06:45:23Z",
  };

  //   // [Optional]:: ==> Future Release ::::::::::::::::::::::::::::::::
  // useEffect(() => {
  //   const documentCookies = document.cookie;
  //   const cookie = convertCookieData(documentCookies);
  //   cookie.map((item, index) => {
  //     // ::::::::::::::::::::::::::::::::::::: Cookie :::::::
  //     if (item?.key === " name") {
  //       setCookieData(item?.value);
  //     }
  //     console.log("cookieData", cookieData);
  //   });
  // }, [inputValue, cookieData]);
  //   // ::::::::::::::::::::::::::::::::::::: <== Future Release:::::::

  const getGithubData = (e: { preventDefault: () => void }) => {
    e.preventDefault();
    if (inputValue !== "") {
    } else {
      alert("Please enter the Github Username!");
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Github-Readme-Design</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.navHeader}>Github-Readme-Design</nav>
      <main className={styles.outerContainer}>
        {errMesage ? (
          <div className={styles.errorContainer}>
            Sorry user not match 😶
            <span
              className={styles.errorContainerClose}
              onClick={(e) => {
                setErrMesage(false);
              }}
            >
              X
            </span>
          </div>
        ) : succMessage ? (
          <div className={styles.succContainer}>
            wow! user matched 🙂
            <span
              className={styles.succContainerClose}
              onClick={(e) => {
                setSuccMessage(false);
              }}
            >
              X
            </span>
          </div>
        ) : (
          <div className={styles.loadContainer}>{loadMessage}</div>
        )}
        {/*  */}
        <div className={styles.repoBoxContainer}>
          {/*  */}
          <div className={styles.repoBoxContainerLabel}>
            <div className={styles.repoBoxContainerLabelIcon}>
              <FontAwesomeIcon icon={faGithub} size={"4x"} style={{}} />
            </div>
            <div className={styles.repoBoxContainerLabelText}>
              Github Username
            </div>
          </div>
          {/*  */}
          <div className={styles.repoBoxContainerInput}>
            <input
              aria-label="repo_name"
              className={styles.repoBoxInput}
              placeholder={"Github Username"}
              value={inputValue}
              onChange={(e) => {
                e.preventDefault();
                setErrMesage(false);
                setSuccMessage(false);
                setInputValue(e.target.value);
                setTimeout(() => {
                  if (e?.target?.value === testGit?.login) {
                    try {
                      //::::::::::::: For future release ::::::::::::::::::::::::>
                      //********* Adding Cookies ********** */
                      // document.cookie = `name=${testGit?.login}; expires=${expires}; path=/;`;
                      // document.cookie = `name=${testGit?.login}; path=/;`;
                      //********************************** */
                      console.log("data :>> ", data);
                    } catch (error) {
                      console.log("Something went wrong!");
                      console.log("error", error);
                    }
                    // if (
                    //   testGit?.login !== "" ||
                    //   testGit?.login !== undefined ||
                    //   testGit?.login !== null
                    // ) {
                    setTimeout(() => {
                      setErrMesage(false);
                      setSuccMessage(true);
                    }, 500);
                  } else if (e?.target?.value === "") {
                    setTimeout(() => {
                      setErrMesage(false);
                      setSuccMessage(false);
                    }, 500);
                  } else {
                    setTimeout(() => {
                      setErrMesage(true);
                      setSuccMessage(false);
                    }, 500);
                  }
                }, 300);
                // console.log("inputValue :>> ", inputValue);
              }}
            />
            <div
              className={styles.repoBoxButton}
              onMouseEnter={(e) => {
                e.preventDefault();
                e.currentTarget.style.color = "#333";
                e.currentTarget.style.transition = "0.3s";
              }}
              onMouseLeave={(e) => {
                e.preventDefault();
                e.currentTarget.style.color = "#bcbcbc";
                e.currentTarget.style.transition = "0.3s";
              }}
              onClick={getGithubData}
            >
              <FontAwesomeIcon icon={faArrowRight} size={"sm"} style={{}} />
            </div>
          </div>
        </div>

        {/* Below the design block */}
        <div className={styles.desingCard}>
          <AllCard />
        </div>
        {/* Above the design block */}
      </main>
      {/*  */}
      {/* <div> */}
      {/*  */}
      {/* <iframe
          src="http://instantmarkdown.herokuapp.com/"
          width="100%"
          height="500"
          style={{ border: "1px solid black" }}
        ></iframe> */}
      {/*  */}
      {/* </div> */}
      {/*  */}
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          {/* instant markdown previewer */}
          Sponsored by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
        <a
          href="https://github.com/hirishu10"
          target="_blank"
          rel="noopener noreferrer"
        >
          Desinged by Rishu Chowdhary{" "}
          <span className={styles.logo}>
            <Image
              src="/rishufavicon.ico"
              alt="Rishu Chowdhary"
              width={30}
              height={30}
            />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
